### PR TITLE
Fixes missing drawable/abc_ic_menu_moreoverflow_mtrl_alpha issue.

### PR DESCRIPTION
**Pull request by JamesWhitfield**

### CODE REVIEW

**Comment by jensck** [comment]
@JamesWhitfield have you signed the CLA?

Also, please revert the changes to the Android Studio "droppings", so the diff consists of just the `build.gradle` changes.

**Comment by JamesWhitfield** [comment]
I have made the 'droppings' changes. How do I sign the CLA?

**Comment by jensck** [comment]
The form is here: https://docs.google.com/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

**Comment by JamesWhitfield** [comment]
Done. Thank you for getting back to me.

**Comment by jensck** [comment]
Looks good, thanks again.

**Pull request merged**
